apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: budget-book
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/choizeus02/budget-book.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: budget-book
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
